# version: '3.9'

services:
  router:
    image: nginx:1.21-alpine
    ports:
      - 8000:80
    volumes:
      - ./.cloudnative/nginx-conf-router:/etc/nginx/conf.d:ro

  frontend:
    build: .
    # ports:
    #   - "7070:80"
# docker run -d -p 8080:8080 -e ADMIN_PASSWORD=pass123 abdennour/dummy-rest-api-example
  api:
    image: abdennour/dummy-rest-api-example
    # ports:
    #   - '9090:8080'
    environment:
      ADMIN_PASSWORD: pass123
  # api-ambassador:
  #   image: nginx:1.21-alpine
  #   ports:
  #     - '9091:80'
  #   volumes:
  #     - ./.cloudnative/nginx-conf-skip-cors:/etc/nginx/conf.d:ro